#!/usr/bin/env bash
# Bahram CM — MySQL + Redis production tuning for high traffic on a shared app VPS.
#
# Usage (on the server, as root):
#   sudo bash /var/www/bahram-cm/deploy/scripts/tune-mysql.sh
#   sudo bash /var/www/bahram-cm/deploy/scripts/tune-mysql.sh --check
#
# Safe to re-run. Does NOT wipe data. Restarts MySQL only when config changes.
set -euo pipefail

CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK_ONLY=1
fi

APP_ROOT="${APP_ROOT:-/var/www/bahram-cm}"
ENV_FILE="${ENV_FILE:-$APP_ROOT/backend/.env}"
MYSQL_CONF_DIR="/etc/mysql/mysql.conf.d"
MYSQL_CONF="$MYSQL_CONF_DIR/99-bahram-innodb.cnf"
REDIS_CONF_DROPIN="/etc/redis/redis.conf.d/99-bahram.conf"
SLOW_LOG="/var/log/mysql/bahram-slow.log"

if [[ ! -d /etc/mysql ]]; then
  echo "ERROR: MySQL does not appear to be installed (/etc/mysql missing)."
  exit 1
fi

TOTAL_MB="$(awk '/MemTotal:/ {print int($2/1024)}' /proc/meminfo)"
# Shared app box (Nginx + PHP-FPM + Node/PM2 + Redis + MySQL):
# leave headroom for the app stack; give InnoDB a large but bounded buffer.
if [[ "$TOTAL_MB" -ge 30000 ]]; then
  BUFFER_MB=12288
elif [[ "$TOTAL_MB" -ge 15000 ]]; then
  BUFFER_MB=6144
elif [[ "$TOTAL_MB" -ge 7000 ]]; then
  # Shared ~8GB VPS (PHP + Next + Redis + MySQL): prefer 2GB InnoDB over 3GB
  # so FPM/Node still have headroom under traffic.
  BUFFER_MB=2048
elif [[ "$TOTAL_MB" -ge 3500 ]]; then
  # Shared ~4GB VPS: leave room for Nginx/PHP/Node/Redis.
  BUFFER_MB=1024
else
  BUFFER_MB=512
fi

# Redis: keep under ~12% of RAM, min 256MB, max 2GB on shared VPS.
REDIS_MB=$(( TOTAL_MB / 8 ))
if [[ "$REDIS_MB" -lt 256 ]]; then REDIS_MB=256; fi
if [[ "$REDIS_MB" -gt 2048 ]]; then REDIS_MB=2048; fi
# On ~8GB shared boxes, cap Redis so MySQL+PHP+Next stay comfortable.
if [[ "$TOTAL_MB" -ge 7000 && "$TOTAL_MB" -lt 15000 && "$REDIS_MB" -gt 768 ]]; then
  REDIS_MB=768
fi

INSTANCES=1
if [[ "$BUFFER_MB" -ge 4096 ]]; then
  INSTANCES=4
elif [[ "$BUFFER_MB" -ge 2048 ]]; then
  INSTANCES=2
fi

echo "==> Host RAM: ${TOTAL_MB}MB"
echo "==> Planned innodb_buffer_pool_size: ${BUFFER_MB}MB (${INSTANCES} instance(s))"
echo "==> Planned Redis maxmemory: ${REDIS_MB}MB"

print_status() {
  echo ""
  echo "==> Current MySQL status"
  mysql -Nse "
    SHOW VARIABLES WHERE Variable_name IN (
      'innodb_buffer_pool_size',
      'innodb_buffer_pool_instances',
      'innodb_flush_method',
      'innodb_redo_log_capacity',
      'max_connections',
      'slow_query_log',
      'long_query_time',
      'tmp_table_size',
      'table_open_cache'
    );
  " 2>/dev/null || echo "WARN: cannot query MySQL (is mysqld up?)"

  echo ""
  echo "==> Redis"
  if command -v redis-cli >/dev/null 2>&1; then
    redis-cli ping 2>/dev/null || echo "WARN: redis-cli ping failed"
    redis-cli INFO memory 2>/dev/null | grep -E '^(used_memory_human|maxmemory_human|maxmemory_policy):' || true
  else
    echo "WARN: redis-cli not found"
  fi

  if [[ -f "$ENV_FILE" ]]; then
    echo ""
    echo "==> Laravel .env store drivers"
    grep -E '^(CACHE_STORE|QUEUE_CONNECTION|SESSION_DRIVER|REDIS_HOST|DB_CONNECTION)=' "$ENV_FILE" || true
  fi
}

print_status

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  exit 0
fi

echo ""
echo "==> Writing $MYSQL_CONF"
mkdir -p "$MYSQL_CONF_DIR" /var/log/mysql
touch "$SLOW_LOG"
chown mysql:mysql "$SLOW_LOG" 2>/dev/null || true

MYSQL_TMP="$(mktemp)"
cat > "$MYSQL_TMP" <<EOF
# Bahram CM — generated by deploy/scripts/tune-mysql.sh
# Host RAM ≈ ${TOTAL_MB}MB — do not hand-edit; re-run the script after RAM upgrades.
[mysqld]
innodb_buffer_pool_size = ${BUFFER_MB}M
innodb_buffer_pool_instances = ${INSTANCES}
innodb_flush_method = O_DIRECT
innodb_redo_log_capacity = 1G
innodb_io_capacity = 800
innodb_io_capacity_max = 2400
innodb_read_io_threads = 6
innodb_write_io_threads = 6
innodb_flush_log_at_trx_commit = 1
innodb_file_per_table = 1

# Connection / temp tables (shared VPS — keep conservative)
max_connections = 200
table_open_cache = 4000
tmp_table_size = 64M
max_heap_table_size = 64M
join_buffer_size = 2M
sort_buffer_size = 2M

# Observability
slow_query_log = 1
slow_query_log_file = ${SLOW_LOG}
long_query_time = 1
log_queries_not_using_indexes = 0

character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
EOF

MYSQL_CHANGED=0
if [[ ! -f "$MYSQL_CONF" ]] || ! cmp -s "$MYSQL_TMP" "$MYSQL_CONF"; then
  cp "$MYSQL_TMP" "$MYSQL_CONF"
  MYSQL_CHANGED=1
fi
rm -f "$MYSQL_TMP"
# mysqld runs as mysql user — mode 600 causes Permission denied and
# aborts the whole includedir (falls back to tiny default buffer pool).
chmod 644 "$MYSQL_CONF"
chown root:root "$MYSQL_CONF"

if [[ "$MYSQL_CHANGED" -eq 1 ]]; then
  echo "==> MySQL config changed — restarting mysqld (brief downtime)"
  systemctl restart mysql
  sleep 2
  systemctl is-active --quiet mysql
else
  echo "==> MySQL config unchanged — skip restart"
fi

echo "==> Ensuring Redis maxmemory + allkeys-lru"
REDIS_CHANGED=0
if [[ -d /etc/redis ]]; then
  mkdir -p /etc/redis/redis.conf.d
  # Ubuntu redis often includes only /etc/redis/redis.conf — append drop-in include if supported,
  # otherwise patch the main conf idempotently.
  if grep -qE '^\s*include\s+/etc/redis/redis\.conf\.d' /etc/redis/redis.conf 2>/dev/null; then
    REDIS_TMP="$(mktemp)"
    cat > "$REDIS_TMP" <<EOF
# Bahram CM — generated by tune-mysql.sh
maxmemory ${REDIS_MB}mb
maxmemory-policy allkeys-lru
EOF
    if [[ ! -f "$REDIS_CONF_DROPIN" ]] || ! cmp -s "$REDIS_TMP" "$REDIS_CONF_DROPIN"; then
      cp "$REDIS_TMP" "$REDIS_CONF_DROPIN"
      REDIS_CHANGED=1
    fi
    rm -f "$REDIS_TMP"
  else
    BEFORE_REDIS="$(mktemp)"
    cp /etc/redis/redis.conf "$BEFORE_REDIS"
    if grep -qE '^\s*maxmemory\s+' /etc/redis/redis.conf; then
      sed -i -E "s|^[[:space:]]*maxmemory[[:space:]].*|maxmemory ${REDIS_MB}mb|" /etc/redis/redis.conf
    else
      echo "maxmemory ${REDIS_MB}mb" >> /etc/redis/redis.conf
    fi
    if grep -qE '^\s*maxmemory-policy\s+' /etc/redis/redis.conf; then
      sed -i -E 's|^[[:space:]]*maxmemory-policy[[:space:]].*|maxmemory-policy allkeys-lru|' /etc/redis/redis.conf
    else
      echo "maxmemory-policy allkeys-lru" >> /etc/redis/redis.conf
    fi
    if ! cmp -s "$BEFORE_REDIS" /etc/redis/redis.conf; then
      REDIS_CHANGED=1
    fi
    rm -f "$BEFORE_REDIS"
  fi
  if [[ "$REDIS_CHANGED" -eq 1 ]]; then
    echo "==> Redis config changed — restarting"
    systemctl restart redis-server 2>/dev/null || systemctl restart redis 2>/dev/null || true
  else
    echo "==> Redis config unchanged — skip restart"
  fi
fi

if [[ -f "$ENV_FILE" ]]; then
  echo "==> Forcing Laravel cache/queue/session onto Redis"
  cd "$APP_ROOT/backend"
  set_env() {
    local key="$1" val="$2"
    if grep -q "^${key}=" "$ENV_FILE"; then
      sed -i "s|^${key}=.*|${key}=${val}|" "$ENV_FILE"
    else
      echo "${key}=${val}" >> "$ENV_FILE"
    fi
  }
  set_env CACHE_STORE redis
  set_env QUEUE_CONNECTION redis
  set_env SESSION_DRIVER redis
  set_env REDIS_HOST 127.0.0.1
  set_env REDIS_PORT 6379
  php artisan config:cache 2>/dev/null || true
fi

echo ""
echo "==> Post-apply verification"
print_status

echo ""
echo "============================================"
echo "MySQL/Redis tuning applied."
echo "  config: $MYSQL_CONF"
echo "  slow log: $SLOW_LOG"
echo "Next: run migrations for high-traffic indexes:"
echo "  cd $APP_ROOT/backend && php artisan migrate --force"
echo "============================================"
