<?php

namespace App\Console\Commands;

use App\Support\LegacyMediaMap;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class ExportLegacyMediaMap extends Command
{
    protected $signature = 'media:export-legacy-map';

    protected $description = 'Export legacy /media and /images path map to frontend/lib/media/legacyMap.generated.ts';

    public function handle(): int
    {
        $map = LegacyMediaMap::all();
        $out = dirname(base_path()).'/frontend/lib/media/legacyMap.generated.ts';

        $lines = ["// Auto-generated by php artisan media:export-legacy-map — do not edit manually.", '', 'export const GENERATED_LEGACY_MAP: Record<string, string> = {'];
        foreach ($map as $legacy => $storage) {
            $legacyJson = json_encode($legacy, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            $storageJson = json_encode($storage, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            $lines[] = "  {$legacyJson}: {$storageJson},";
        }
        $lines[] = '};';
        $lines[] = '';

        File::put($out, implode("\n", $lines));
        $this->info('Exported '.count($map)." legacy paths to {$out}");

        return self::SUCCESS;
    }
}
