<?php

namespace App\Console\Commands;

use App\Services\MediaHostSettingsService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class SyncMediaHosts extends Command
{
    protected $signature = 'media:sync-hosts
        {--export : Write database/data/media_hosts.json from the settings table}
        {--import : Apply database/data/media_hosts.json into the database (default)}';

    protected $description = 'Sync download-host URLs between git-tracked JSON, database settings, and frontend generated file';

    public function handle(MediaHostSettingsService $hosts): int
    {
        if ($this->option('export')) {
            return $this->exportManifest($hosts);
        }

        return $this->importManifest($hosts);
    }

    private function importManifest(MediaHostSettingsService $hosts): int
    {
        $manifest = $hosts->manifestDefaults();
        if ($manifest === []) {
            $this->error('Missing or invalid '.MediaHostSettingsService::MANIFEST);

            return self::FAILURE;
        }

        $hosts->importFromManifest();
        $this->exportFrontend($hosts->publicView());
        $this->info('Imported media host settings from '.MediaHostSettingsService::MANIFEST);

        return self::SUCCESS;
    }

    private function exportManifest(MediaHostSettingsService $hosts): int
    {
        $view = $hosts->publicView();
        $payload = [
            'version' => 1,
            'media_url' => $view['media_url'] ?? 'https://cdn.rostami.app',
            'family_media_cdn_url' => $view['family_media_cdn_url'] ?? 'https://cdn.rostami.app',
        ];

        $path = base_path(MediaHostSettingsService::MANIFEST);
        File::ensureDirectoryExists(dirname($path));
        File::put(
            $path,
            json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)."\n",
        );

        $this->exportFrontend($view);
        $this->info('Exported media host settings to '.MediaHostSettingsService::MANIFEST);

        return self::SUCCESS;
    }

    /** @param  array{media_url: string|null, family_media_cdn_url: string|null}  $view */
    private function exportFrontend(array $view): void
    {
        $mediaUrl = $view['media_url'] ?? 'https://cdn.rostami.app';
        $familyUrl = $view['family_media_cdn_url'] ?? $mediaUrl;
        $out = dirname(base_path()).'/frontend/lib/media/hosts.generated.ts';

        $content = implode("\n", [
            '// Auto-generated by php artisan media:sync-hosts — do not edit manually.',
            '',
            'export const MEDIA_HOSTS = {',
            "  media_url: '".addslashes($mediaUrl)."',",
            "  family_media_cdn_url: '".addslashes($familyUrl)."',",
            '} as const;',
            '',
        ]);

        File::put($out, $content);
        $this->info("Exported frontend hosts to {$out}");
    }
}
