import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  Briefcase,
  CalendarClock,
  CalendarDays,
  Circle,
  CircleDollarSign,
  ClipboardList,
  CreditCard,
  ExternalLink,
  Eye,
  FileUp,
  FolderOpen,
  Gift,
  GraduationCap,
  HelpCircle,
  Image,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  LifeBuoy,
  LogOut,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareQuote,
  Minimize2,
  Newspaper,
  Palette,
  PanelRightClose,
  PanelRightOpen,
  PenLine,
  Pencil,
  PlayCircle,
  Receipt,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Users,
  Wallet,
  Zap,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/** Tree-shaken icon map for admin UI — avoids `import * as Icons from 'lucide-react'`. */
export const adminLucideIcons: Record<string, LucideIcon> = {
  Activity,
  BarChart3,
  Bell,
  Bot,
  Briefcase,
  CalendarClock,
  CalendarDays,
  Circle,
  CircleDollarSign,
  ClipboardList,
  CreditCard,
  ExternalLink,
  Eye,
  FileUp,
  FolderOpen,
  Gift,
  GraduationCap,
  HelpCircle,
  Image,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  LifeBuoy,
  LogOut,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareQuote,
  Minimize2,
  Newspaper,
  Palette,
  PanelRightClose,
  PanelRightOpen,
  PenLine,
  Pencil,
  PlayCircle,
  Receipt,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Users,
  Wallet,
  Zap,
};

export function AdminLucideIcon({
  name,
  className,
  strokeWidth = 1.6,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = adminLucideIcons[name] ?? Circle;
  return <Cmp className={cn(className)} strokeWidth={strokeWidth} />;
}
