// Auto-generated by scripts/generate-version.mjs — do not edit.
export const BUILD_VERSION = "3.0.0";
export const BUILD_NAME = "bahram";
export const BUILD_HASH = "ms9h93pa-2503c2";
export const BUILD_TIME = "2026-07-31T21:51:29.278Z";
