// Auto-generated by scripts/generate-version.mjs — do not edit.
export const BUILD_VERSION = "3.0.0";
export const BUILD_NAME = "bahram";
export const BUILD_HASH = "msgb9to1-6a2b07";
export const BUILD_TIME = "2026-08-05T16:38:28.466Z";
