// Auto-generated by scripts/generate-version.mjs — do not edit.
export const BUILD_VERSION = "3.0.0";
export const BUILD_NAME = "bahram";
export const BUILD_HASH = "mrwpt36a-60ea3c";
export const BUILD_TIME = "2026-07-22T23:29:58.354Z";
