#!/usr/bin/env node
/**
 * Writes public/version.json and lib/pwa/build-info.generated.ts at build time.
 * Controls optional/forced/silent update UX via BAHRAM_UPDATE_TYPE env.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = pkg.version || '0.1.0';
const buildHash = `${Date.now().toString(36)}-${crypto.randomBytes(3).toString('hex')}`;
const buildTime = new Date().toISOString();
const updateType = process.env.BAHRAM_UPDATE_TYPE || 'optional';
const buildName = process.env.BAHRAM_BUILD_NAME || 'bahram';

const versionData = {
  version,
  name: buildName,
  buildHash,
  buildTime,
  timestamp: Date.now(),
  updateType,
  minVersion: version,
};

fs.writeFileSync(path.join(root, 'public/version.json'), `${JSON.stringify(versionData, null, 2)}\n`);

const ts = `// Auto-generated by scripts/generate-version.mjs — do not edit.
export const BUILD_VERSION = ${JSON.stringify(version)};
export const BUILD_NAME = ${JSON.stringify(buildName)};
export const BUILD_HASH = ${JSON.stringify(buildHash)};
export const BUILD_TIME = ${JSON.stringify(buildTime)};
`;

fs.mkdirSync(path.join(root, 'lib/pwa'), { recursive: true });
fs.writeFileSync(path.join(root, 'lib/pwa/build-info.generated.ts'), ts);

console.log(`[generate-version] ${version} (${buildHash}) name=${buildName} updateType=${updateType}`);
