// Auto-generated by php artisan media:sync-hosts — do not edit manually.

export const MEDIA_HOSTS = {
  media_url: 'https://cdn.rostami.app',
  family_media_cdn_url: 'https://cdn.rostami.app',
} as const;
