/** @type {import('pm2').StartOptions} */
module.exports = {
  apps: [
    {
      name: 'bahram-frontend',
      cwd: '/var/www/bahram-cm/frontend',
      script: '/var/www/bahram-cm/deploy/pm2/next-prod.cjs',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      min_uptime: '30s',
      max_restarts: 30,
      restart_delay: 4000,
      exp_backoff_restart_delay: 200,
      kill_timeout: 8000,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NODE_OPTIONS: '--max-old-space-size=768',
      },
      error_file: '/var/log/pm2/bahram-frontend-error.log',
      out_file: '/var/log/pm2/bahram-frontend-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'family-manager-web',
      cwd: '/var/www/foroushino/bahram-family-manager',
      script: 'npx',
      args: '--yes serve -s build/web -l 7358',
      interpreter: 'none',
      autorestart: true,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/pm2/family-manager-web-error.log',
      out_file: '/var/log/pm2/family-manager-web-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
