<?php

declare(strict_types=1);

/**
 * Enable Laravel host bridge for local `telegram/` and write config.php.
 *
 *   php _local_enable_host.php
 */

require __DIR__.'/../bahram-cm/backend/vendor/autoload.php';
$app = require __DIR__.'/../bahram-cm/backend/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Modules\TelegramBot\Models\TelegramBot;
use App\Services\SettingService;
use App\Services\TelegramInfrastructureService;
use App\Jobs\PushTelegramHostSyncJob;
use Illuminate\Support\Str;

$infra = app(TelegramInfrastructureService::class);
$settings = app(SettingService::class);

$hostBase = 'http://127.0.0.1:8088';
$syncBase = 'http://127.0.0.1:8010/api/v1/integrations/telegram-host';

// Read PROXY_SHARED_TOKEN / TELEGRAM_API_BASE_URL from Laravel .env (already loaded).
$apiBase = rtrim((string) config('telegram_bot.api.base_url', env('TELEGRAM_API_BASE_URL', '')), '/');
$apiBearer = (string) (config('telegram_bot.api.proxy_shared_token')
    ?? env('PROXY_SHARED_TOKEN', ''));

// Direct write — SsrfGuard blocks private HTTP URLs via admin update().
$ref = new ReflectionClass($infra);
$storedMethod = $ref->getMethod('stored');
$storedMethod->setAccessible(true);
/** @var array<string, mixed> $next */
$next = $storedMethod->invoke($infra);

$next['bridge_type'] = 'host';
$next['base_url'] = $hostBase;
unset($next['secondary_base_url']);

if (trim((string) ($next['host_sync_secret'] ?? '')) === '') {
    $next['host_sync_secret'] = Str::random(64);
}
if (trim((string) ($next['webhook_secret'] ?? '')) === '') {
    $next['webhook_secret'] = Str::random(32);
}

$ensure = $ref->getMethod('ensureWebhookSecret');
$ensure->setAccessible(true);
$ensure->invokeArgs($infra, [&$next]);

$settings->updateGroup(TelegramInfrastructureService::GROUP, [
    TelegramInfrastructureService::KEY => $next,
]);
TelegramInfrastructureService::forgetCachedConfig();

$bot = TelegramBot::query()->where('key', 'production')->first();
$botToken = (string) ($bot?->resolveToken() ?? '');
if ($botToken === '') {
    fwrite(STDERR, "Production bot token missing in panel.\n");
    exit(1);
}

$siteBase = rtrim((string) config('telegram.site_base_url', 'https://rostami.app'), '/');

$config = <<<PHP
<?php

declare(strict_types=1);

/**
 * Local host app config — generated by _local_enable_host.php (gitignored).
 */
return [
    'sync_base_url' => '{$syncBase}',
    'host_sync_token' => '{$next['host_sync_secret']}',
    'proxy_origin' => 'Telegram-Host-App',
    'server_push_origin' => 'Main-Server',
    'host_public_url' => '{$hostBase}',
    'webhook_secret' => '{$next['webhook_secret']}',
    'bot_token' => '{$botToken}',
    'telegram_api_base_url' => '{$apiBase}',
    'telegram_api_bearer' => '{$apiBearer}',
    'site_base_url' => '{$siteBase}',
    'db' => [
        'host' => '127.0.0.1',
        'port' => 3306,
        'database' => 'telegram_host_local',
        'username' => 'root',
        'password' => '',
        'charset' => 'utf8mb4',
    ],
    'iran_relay_per_webhook' => 2,
    'pull_sync_enabled' => false,
    'pull_sync_min_interval_seconds' => 3600,
    'membership_cache_ttl_seconds' => 900,
    'cache_ttl_seconds' => 300,
];

PHP;

file_put_contents(__DIR__.'/config.php', $config);

// Prefer local HTTP push (hostAppBaseUrl would rewrite to https://).
$envPath = __DIR__.'/../bahram-cm/backend/.env';
$env = is_file($envPath) ? (string) file_get_contents($envPath) : '';
$pushLine = 'TELEGRAM_HOST_PUSH_URL=http://127.0.0.1:8088/public/host-sync.php';
if (preg_match('/^TELEGRAM_HOST_PUSH_URL=.*/m', $env) === 1) {
    $env = preg_replace('/^TELEGRAM_HOST_PUSH_URL=.*/m', $pushLine, $env) ?? $env;
} else {
    $env = rtrim($env)."\n\n{$pushLine}\n";
}
file_put_contents($envPath, $env);

echo "Host bridge enabled (base={$hostBase})\n";
echo "Wrote telegram/config.php\n";
echo "Set {$pushLine}\n";
echo "Pushing bootstrap/catalog to local host…\n";

try {
    PushTelegramHostSyncJob::all();
    echo "PushTelegramHostSyncJob::all() dispatched/ran.\n";
} catch (Throwable $e) {
    echo 'Push warning: '.$e->getMessage()."\n";
}

echo "Done. Next: php bin/local-poll.php\n";
